"""Package metadata"""
TITLE = "rabbit_force"
DESCRIPTION = "Salesforce Streaming API to RabbitMQ adapter service"
KEYWORDS = ""
URL = ""
VERSION = "0.1.0"
AUTHOR = "Róbert Márki"
AUTHOR_EMAIL = "gsmiko@gmail.com"
